### ISSUE TITLE
v1.14 upgrade issue:  <TextBox

### ISSUE THREAD

**Issue by mikezimm** [mikezimm/generic-solution#154]
## Lots of these errors from TextBox onChanged update...

![image](https://user-images.githubusercontent.com/49648086/187807630-8652d697-f7a4-45aa-aebc-a272e95beba6.png)

```bash
sp-pages-assembly_en-us_e149dc38213e056cff23d3bacce78572.js:69 
        
       Uncaught TypeError: text.toLowerCase is not a function
    at QZ/U.InspectLists.getNewFilteredItems (listsComponent.tsx:839:41)
    at InspectLists._this.searchForLists (listsComponent.tsx:856:55)
    at InspectLists._this._searchForItems (listsComponent.tsx:825:10)
    at 8Fwr.SearchBoxBase._callOnChange (SearchBox.base.js:168:1)
    at SearchBoxBase._this._onInputChange (SearchBox.base.js:78:1)
    at Object.s (sp-pages-assembly_en-us_e149dc38213e056cff23d3bacce78572.js:69:6402)
    at p (sp-pages-assembly_en-us_e149dc38213e056cff23d3bacce78572.js:69:6545)
    at sp-pages-assembly_en-us_e149dc38213e056cff23d3bacce78572.js:69:6691
    at b (sp-pages-assembly_en-us_e149dc38213e056cff23d3bacce78572.js:69:6777)
    at rt (sp-pages-assembly_en-us_e149dc38213e056cff23d3bacce78572.js:69:22213)
```

**Comment by mikezimm** [comment]
## Need to change all Search/Text box functions 
look for typeof === string first, if not, then look at target.value

```javascript
  public searchForLists = (input: any, meta: string): void => {

    const text = typeof input === 'string' ? input : input && input.target && input.target.value ? input.target.value : '';

```
